name: Jobs (Hourly Diff) -> Email

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allow manual trigger for testing

jobs:
  hourly_diff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml markdown

      - name: Run hourly (only new jobs)
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENTS_JSON: ${{ secrets.RECIPIENT }}
          SOURCE_URL: https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/README.md
        run: |
          python scripts/hourly_diff_jobs.py

      - name: Commit state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state/sent.json || true
          git commit -m "chore: update sent state" || echo "No changes"
          git push || true
