name: Jobs Scraper → Email (SMTP)

on:
  workflow_dispatch: # manual runs always send latest 50 and save their IDs
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  scrape_and_send_jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to commit state/sent.json
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: keep real addresses out of a public repo
      - name: Write recipients.json from secret (optional)
        if: ${{ secrets.RECIPIENTS_JSON != '' }}
        run: |
          echo '${{ secrets.RECIPIENTS_JSON }}' > recipients.json

      - name: Scrape & send (manual = latest 50; cron = only new)
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          SOURCE_URL: "https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/README.md"
        run: |
          # Detect if this is a manual run
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            python scripts/scrape_send.py --manual
          else
            python scripts/scrape_send.py
          fi

      - name: Commit state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state/sent.json || true
          git commit -m "chore: update sent state" || echo "No changes"
          git push || echo "No changes"
