name: Jobs Scraper → Email (SMTP)
on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *" # daily 06:15 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to commit state/sent.json
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape & send email
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }} # e.g. smtp.gmail.com
          SMTP_PORT: ${{ secrets.SMTP_PORT }} # e.g. 587
          SMTP_USER: ${{ secrets.SMTP_USER }} # sender email
          SMTP_PASS: ${{ secrets.SMTP_PASS }} # app password
          SOURCE_URL: "https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/README.md"
        run: |
          python scripts/scrape_send.py

      - name: Commit state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state/sent.json || true
          git commit -m "chore: update sent state" || echo "No changes"
          git push || echo "No changes"
